permalink:   none
lsi:         false
pygments:    true
destination: public
markdown:    rdiscount
rdiscount:   { extensions: [smart] }
exclude:
  - script
  - Guardfile
  - README.markdown

title: "Why's (Poignant) Guide to Ruby"
